dotenv/src/lib.rs

Also simplify fully-qualified references in the docs. I can change that if you liked the existing fully-qualified names better.

Use doc links for docs that reference other items

---

dotenv/src/lib.rs

This will allow reading env vars from any arbitrary `io::Read`.
Use case: I'm working on a tool to translate a dhall file into a dotenv file, and a tool to load dotenv files into the fish shell.
I'd like to run `dhallenv file.dhall | fishdotenv`, which requires reading a dotenv formatted stream from stdin.
(Yes, I could use `from_filename_iter("/dev/stdin")`, but that's a bit non-obvious, and feels a little hacky.)
I considered exposing `Iter` directly, but that seems like an implementation detail.
I didn't add additional unit tests because it doesn't really add any new code paths. If that's not okay, I'll happily add some.

Add `from_read` and `from_read_iter`.

---

dotenv/src/iter.rs
dotenv/tests/test-multiline.rs

A small improvement over PR https://github.com/dotenv-rs/dotenv/pull/63, as suggested [in a comment there](https://github.com/dotenv-rs/dotenv/pull/63#discussion_r677892761).
Fixes issue https://github.com/dotenv-rs/dotenv/issues/40

Add multiline support

---

dotenv/src/iter.rs
dotenv/tests/test-multiline-comment.rs

Support parsing lines that contain comments & quotes.
Previously this input:
```
TESTKEY=test_val # A '" comment
```
Would fail the regression test (`test_issue_12`):
```
running 1 test
test test_issue_12 ... FAILED
failures:
---- test_issue_12 stdout ----
thread 'test_issue_12' panicked at 'should succeed: LineParse("# Comment line with single ' quote\n# Comment line with double \" quote\n # Comment line with double \" quote and starts with a space\nTESTKEY=test_val # A '\" comment\n# End of .env file\n", 181)', dotenv/tests/test-multiline-comment.rs:21:14
stack backtrace:
0: rust_begin_unwind
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:1 …
```

fix: support comments in multiline input

---

.env
dotenv/examples/list_variables.rs
dotenv/src/iter.rs
dotenv/tests/test-multiline-comment.rs

This PR fixes #12
Added a WhiteSpace ParseState and check for a comment after a
whitespace. Also return the current position of the iter to correctly
strip the comments of from the line to prevent quoted comments or
non-whitespace surrounded hash chars.
Also updated the tests to match these cases.
And added an example code to easily show the output.

Fix comments reggression

---

.github/workflows/rust.yml
dotenv/src/iter.rs

Also start testing against that release as an MSRV.
Suggested resolution of #20.

Remove destructuring assignment for compatibility with Rust 1.58.1

---

dotenv/src/errors.rs
dotenv/src/parse.rs

- Remove unnecessary reference
- Use #[non_exhaustive]` annotation on `dotenvy::Error` enum
The second one is technically an incompatible API change. However, the whole point of the `__Nonexhaustive` variant pattern is to get callers to include a wildcard branch when matching, so you could argue it doesn't require a semver bump: anyone referring to that variant explicitly was doing it wrong. But I don't know if that's the normal expectation; this pattern is new to me.

Fix clippy lints

---

dotenv/Cargo.toml

`dirs` is only used in doctests, not in the library itself. So there is no need to install it for end users.

deps: move `dirs` to dev-dependencies

---

dotenv/src/iter.rs
dotenv/tests/test-ignore-bom.rs

The UTF-8 Byte Order Mark `\ufeff` will be ignored when parsing.
Add integration test to confirm.
See #27

Add support for UTF-8 BOM encoding

---

dotenv/Cargo.toml
dotenv/src/parse.rs
dotenv_codegen/Cargo.toml
dotenv_codegen_impl/Cargo.toml

Clippy lints:
- Single-character string constant used as pattern.
- Use of `.unwrap_or_else(..)` to construct default value.
Cargo warning:
"Previously Unused manifest key: package.rust" warning fixed. The
manifest key according to [Cargo docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) should be `rust-version`.

Fix warnings

---

.github/workflows/ci.yml
.github/workflows/codecov-comment.yml

CI workflow that adds a code coverage comment to pull requests.
- Only runs if all the other checks pass
- Replaces comment on subsequent re-runs

ci: add codecov comment to PRs

---

dotenv/src/lib.rs

Correctly enclose the example on a code block.
Ref: https://docs.rs/dotenvy/0.15.6/dotenvy/fn.vars.html

Fix doc for `vars` function

---

README.md
dotenv/README.md

Add these badges to the readme:
- [![Crates.io](https://img.shields.io/crates/v/dotenvy.svg)](https://crates.io/crates/dotenvy)
- [![msrv
1.58.1](https://img.shields.io/badge/msrv-1.58.1-dea584.svg?logo=rust)](https://github.com/rust-lang/rust/releases/tag/1.58.1)
- [![ci](https://github.com/allan2/dotenvy/actions/workflows/ci.yml/badge.svg)](https://github.com/allan2/dotenvy/actions/workflows/ci.yml)
- [![docs](https://img.shields.io/docsrs/dotenvy?logo=docs.rs)](https://docs.rs/dotenvy/)
Are there any others we should want?

docs: add readme badges

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
dotenv/Cargo.toml
dotenv/README.md
dotenv/examples/list_variables.rs
dotenv/src/lib.rs
dotenv_codegen/Cargo.toml
dotenv_codegen_impl/Cargo.toml

Closes #33 
- Remove format strings in doctests.
- Update `Cargo.toml`s.
- Update docs.
- Add MSRV policy to readmes.
>We aim to support the latest 8 rustc versions - approximately 1 year.
>Increasing MSRV is _not_ considered a semver-breaking change.
Copied from: [once_cell](https://docs.rs/once_cell/latest/once_cell/#minimum-supported-rustc-version).

Add support for Rust 1.56.1

---

README.md
dotenv/README.md
dotenv/src/lib.rs

fixes https://github.com/allan2/dotenvy/issues/37
Hope I've done this correctly🥲

remove unnecessary ok on dotenv result

---

README.md
dotenv/README.md
dotenv_codegen/README.md

The dotenvy_codegen crate was renamed to dotenvy_macro (#2, cd0e6043fb4a80a6ae8924f99a413c2efaddb536) but it is still called dotenvy_codegen a lot in the docs. This fixes this. Especially because the links still pointed to the yanked crate.

docs: change dotenvy_codegen to dotenvy_macro

---

dotenv/src/iter.rs
dotenv/src/lib.rs
dotenv/tests/common/mod.rs
dotenv/tests/test-default-location-overload.rs
dotenv/tests/test-default-location-override.rs
dotenv/tests/test-from-filename-overload.rs
dotenv/tests/test-from-filename-override.rs
dotenv/tests/test-from-filename.rs
dotenv/tests/test-from-path-overload.rs
dotenv/tests/test-from-path-override.rs
dotenv/tests/test-from-read-overload.rs
dotenv/tests/test-from-read-override.rs
dotenv/tests/test-from-read.rs

This is a successor to https://github.com/allan2/dotenvy/pull/17 and the preferred alternative to https://github.com/allan2/dotenvy/pull/46.
- Adds overriding variants to all relevant public API methods.
- Fixes documentation.
- Adds missing test for `from_read()`.
- Tests non-overriding behavior with greater precision.
- Tests overriding behavior correctly.
- Fixes some inconsistent test formatting.
- *Difference from #46:* Fixes inconsistent naming. See discussion in #46 for details.

feat: Implement overriding API methods and correct inconsistent naming

---

dotenv/Cargo.toml
dotenv/tests/integration/main.rs
dotenv/tests/integration/util/mod.rs
dotenv/tests/integration/util/testenv.rs

Candidate for solution to #58 part one.
Setup single-process integration testing with a utility module. Designed so multiple tests can be run without the need for separate processes. In practice, this means new tests will not need a new file. It allows for easily repeating checks across similar functions e.g. `dotenv()` and `from_filename(".env")`.
The heart of the utility module is the `TestEnv` struct which enables controlled setup of a temporary testing environment. When using the `test_in_env` functions, access to the process' environment is effectively locked using a mutex, reset, and then the `TestEnv` is created.
Also included:
- a set of default keys and values
- valid and invalid default envfile contents
- assertions with contextual output when tests fail
```rust
#[test]
fn …
```

test: create test harness with locked environment

---

CONTIRBUTING.md
README.md

docs: add contribution guide

---

examples/.env
examples/Cargo.toml
examples/dev-prod/Cargo.toml
examples/dev-prod/src/main.rs

Many recurring questions from users are about overriding or how to handle errors when a .env file is found or not found.
This PR
- creates an *examples* directory
- adds an example showing how behaviour can differ across dev and prod modes

Add dev prod example

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
dotenv/Cargo.toml
dotenv/README.md
dotenv_codegen/Cargo.toml

Our Minimum Supported Rust Verison [policy](https://github.com/allan2/dotenvy#minimum-supported-rust-version) is to support the last 8 rustc versions. As of 2023-08-08 that is from version 1.63.0 onwards.
Clap's MSRV is [1.64.0](https://github.com/clap-rs/clap/blob/ee1388c0a31fcf0f60a7a93b70e1b20058df6832/.github/workflows/ci.yml#L87C14-L87C14), and we have a [PR](#77) to update to the lastest version. So I have bumped our MSRV to match.
The current CI tests do not pass with version 1.56.1 (due to dependencies having newer MSRVs) so I think it is worth doing now.

Update MSRV to 1.64.0

---

dotenv/Cargo.toml
dotenv/src/bin/dotenvy.rs

This PR updates clap to the newest version.
I was using dotenvy in a project and I saw it duplicating my clap dependency due to using an old version.
This change doesn't break anything as far as I'm aware as we don't expose any of clap's internals ourselves.

Update clap to newest version

---

dotenv/src/lib.rs

When the CI tries to generate the documentation, it fails with
error: redundant explicit link target
Error:    --> dotenv/src/lib.rs:218:51
|
218 | /// Loads environment variables from [`io::Read`](std::io::Read).
|                                       ----------  ^^^^^^^^^^^^^ explicit target is redundant
|                                       |
|                                       because label contains path that resolves to same destination
|
= note: when a link's destination is not specified,
the label is used to resolve intra-doc links
= note: `-D rustdoc::redundant-explicit-links` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(rustdoc::redundant_explicit_links)]`
help: remove explicit link target
|
218 | /// Loads environment variables from …

Remove redundant explicit link target in documentation

---

dotenv/src/find.rs

Simply changes "path not found" to something slightly more descriptive, anything would work here.
I ran into the issues today while deploying a docker container just receiving the error: 
```
Error: path not found
Caused by:
path not found
````
Often dotenvy is being loaded at the beginning of projects, and this error isn't super descriptive, I took (far too long) realizing what path was not being found, as I wasn't copying over my .env to my runtime environment.
I think a change like this could help avoid any silly mistakes for others in the future, but if not no problem, just a suggestion!

Updated path not found error to be a bit more descriptive.

---

CONTRIBUTING.md
dotenv/src/bin/dotenvy.rs
scripts/cicheck.sh

This adds a shell script to quickly run the same checks as the GitHub workflow. This should make it easier for people to contribute.
In the future we can add a script for windows.

Add CI check script

---

dotenv/src/lib.rs

Changed the `#![cfg(unix)]` into multiple `#[cfg(unix)]`, to allow the doctests to compile on Windows

Reworked doctests to be able to compile on Windows

---

dotenvy-macros/src/lib.rs

Currently, in the current code, the `required` attribute does not work as expected. On the code path where it should "continue if not required" actually just fallback into the error printing and process exiting.
Small reproducible example:
```rust
#[dotenvy::load(required = false)]
#[tokio::main]
async fn main() {
let _ = env::var("SOME_VAR").unwrap();
}
```
Which errors out with:
```
Failed to load env file from path './.env': error reading './.env':, No such file or directory (os error 2)
```

fix: correct check for required attribute
